// Generated by CoffeeScript 1.11.1
var Gio, Util;

Gio = imports.gi.Gio;

export default Util = (function() {
  function Util() {}

  Util.readFile = function(filename) {
    var data, file, length, ref, success;
    file = Gio.file_new_for_path(filename);
    ref = file.load_contents(null), success = ref[0], data = ref[1], length = ref[2];
    return data;
  };

  return Util;

})();
