// Generated by CoffeeScript 1.11.1
var AvProperties, GObject, Gtk, Pango,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

GObject = imports.gi.GObject;

Gtk = imports.gi.Gtk;

Pango = imports.gi.Pango;

import PropertyViewer from 'tabs/PropertyViewer';


/*
 *
 * ProjectViewer class - 
 *
 * view autovala data
 *
 */

export default AvProperties = (function(superClass) {
  extend(AvProperties, superClass);

  function AvProperties(prj) {
    this.prj = prj;
  }

  AvProperties.prototype.buildUI = function() {
    var item, key, ref;
    AvProperties.__super__.buildUI.call(this);
    ref = this.prj.data;
    for (key in ref) {
      item = ref[key];
      if (!Array.isArray(item)) {
        this.add(key, item.value, item.readonly);
      }
    }
    return this.grid;
  };

  return AvProperties;

})(PropertyViewer);
