// Generated by CoffeeScript 1.11.1
var GObject, Gtk, Pango, PropertyViewer;

GObject = imports.gi.GObject;

Gtk = imports.gi.Gtk;

Pango = imports.gi.Pango;


/*
 *
 * ProjectViewer class - 
 *
 * view autovala data
 *
 */

export default PropertyViewer = (function() {
  function PropertyViewer(prj) {
    this.prj = prj;
  }

  PropertyViewer.prototype.buildUI = function() {
    this.listStore = new Gtk.ListStore();
    this.listStore.set_column_types([GObject.TYPE_STRING, GObject.TYPE_STRING, GObject.TYPE_STRING]);
    this.treeView = new Gtk.TreeView({
      expand: true,
      model: this.listStore
    });
    this.label = new Gtk.Label({
      label: ""
    });
    this.selection = this.treeView.get_selection();
    this.selection.connect('changed', (function(_this) {
      return function() {
        return _this._onSelectionChanged();
      };
    })(this));
    return this.grid = new Gtk.Grid;
  };

  PropertyViewer.prototype._onSelectionChanged = function() {
    var isSelected, iter, model, ref;
    ref = this.selection.get_selected(), isSelected = ref[0], model = ref[1], iter = ref[2];
    return this.label.set_label("\n" + this.listStore.get_value(iter, 0) + " " + this.listStore.get_value(iter, 1) + " " + this.listStore.get_value(iter, 2) + "\n");
  };

  return PropertyViewer;

})();
