// Generated by CoffeeScript 1.11.1
(function() {
  var App, AppWindow, GLib, Gio, Gtk, Lang, app, readFile;

  Lang = imports.lang;

  GLib = imports.gi.GLib;

  Gio = imports.gi.Gio;

  Gtk = imports.gi.Gtk;

  readFile = function(filename) {
    var data, file, length, ref, success;
    file = Gio.file_new_for_path(filename);
    ref = file.load_contents(null), success = ref[0], data = ref[1], length = ref[2];
    return data;
  };

  App = (function() {
    function App() {
      this.application = new Gtk.Application({
        application_id: 'org.example.myapp',
        flags: Gio.ApplicationFlags.FLAGS_NONE
      });
      this.application.connect('activate', (function(_this) {
        return function() {
          return _this.activate();
        };
      })(this));
    }

    App.prototype.activate = function() {
      this.window = new AppWindow({
        application: this.application
      }).window;
      this.window.present();
    };

    return App;

  })();

  AppWindow = (function() {
    var _AppWindow;

    _AppWindow = Lang.Class({
      Name: 'AppWindow',
      Extends: Gtk.ApplicationWindow,
      Template: readFile('../data/hello.glade'),
      Children: ['label', 'button'],
      _init: function(params, outer) {
        this.parent(params);
        this.label.set_text('Hello, World!');
        this.button.connect('clicked', (function(_this) {
          return function() {
            return _this.application.quit();
          };
        })(this));
      }
    });

    function AppWindow(params) {
      this.window = new _AppWindow(params, this);
    }

    return AppWindow;

  })();

  app = new App();

  app.application.run(ARGV);

}).call(this);
