// Generated by CoffeeScript 1.11.1
(function() {
  var Example, GObject, Gio, Gtk, Lang, Pango, app, readFile;

  Lang = imports.lang;

  GObject = imports.gi.GObject;

  Gtk = imports.gi.Gtk;

  Gio = imports.gi.Gio;

  Pango = imports.gi.Pango;

  readFile = function(filename) {
    var data, file, length, ref, success;
    file = Gio.file_new_for_path(filename);
    ref = file.load_contents(null), success = ref[0], data = ref[1], length = ref[2];
    return data;
  };

  Example = (function() {
    Example.prototype.Name = 'TreeView Example with Simple ListStore';

    function Example() {
      this.application = new Gtk.Application({
        application_id: 'org.example.example'
      });
      this.application.connect('activate', (function(_this) {
        return function() {
          return _this._onActivate();
        };
      })(this));
      this.application.connect('startup', (function(_this) {
        return function() {
          return _this._onStartup();
        };
      })(this));
    }

    Example.prototype._onActivate = function() {
      return this._window.present();
    };

    Example.prototype._onStartup = function() {
      return this._buildUI();
    };

    Example.prototype._buildUI = function() {
      return this._window = new Gtk.ApplicationWindow({
        application: this.application,
        window_position: Gtk.WindowPosition.CENTER,
        default_height: 250,
        default_width: 100,
        border_width: 20,
        Template: readFile('hello.glade'),
        title: "My Phone Book"
      });
    };

    return Example;

  })();

  app = new Example();

  app.application.run(ARGV);

}).call(this);
